settings:
  title: 'IC Tox Lab System Status'
  url: 'https://status.ictoxlab.com/' # used for Slack messages
  logo: logo-color.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-ictoxlab-com # unique identifier
    name: ictoxlab.com
    url: 'https://ictoxlab.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www-help-ictoxlab-com
    name: help.ictoxlab.com
    url: 'https://help.ictoxlab.com'
    method: GET
    expectStatus: 200
    followRedirect: true # should follow
    
  - id: mytoxlabsso
    name: MyToxLab SSO
    url: 'https://login.microsoftonline.com/a352cf2e-213f-4d2a-9df8-3919c48dcc20/oauth2/authorize?response_type=code&scope=openid&domain_hint=https%3A%2F%2Fictoxlab.com&client_id=d2b2969d-001d-4cf3-b89b-7f3a56494c8b&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2Fictoxlab.com%2Flogin%2F&state=%7B77B8A5C1-000A-4570-5957-9CAA78C192F7%7D&nonce=%7B77B8A5C1-000A-4570-5957-9CAA78C192F7%7D&sso_reload=true'
    method: GET
    expectStatus: 200
    followRedirect: true # should follow
    
  - id: simple-in-out
    name: Simple In/Out
    url: 'https://www.simpleinout.com/'
    method: GET
    expectStatus: 200
    followRedirect: false # should follow
